-- Eleutheria: every migration, in order.
-- Paste this whole file into the Supabase SQL editor and run it once.
-- Generated by scripts/apply-migrations.mjs; edit the files in db/migrations instead.


-- ======================================================== 0001_schema.sql --

-- Eleutheria operations database.
--
-- Everything the dashboard owns lives in its own schema, `ops`. The website
-- already has tables in `public`, and this migration must not touch, rename or
-- shadow any of them: a separate schema makes that a guarantee rather than a
-- promise. The only thing added to `public` is one read-only view, in
-- 0002_security.sql, which is what the website reads.
--
-- Mirrors src/types/index.ts. Nested arrays in the front-end model become
-- child tables here so they can be queried and constrained.
--
-- Bilingual values are two columns, not JSON: the app sorts and filters on
-- them, and a column is cheaper to index than a JSON path.
--
-- Money is numeric(12,2). Never float: 0.1 + 0.2 must equal 0.3 in a ledger.

create schema if not exists ops;

-- ---------------------------------------------------------------- helpers --

create or replace function ops.set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ------------------------------------------------------------- reference --

create table if not exists ops.countries (
  id          uuid primary key default gen_random_uuid(),
  name_en     text not null,
  name_ar     text not null default '',
  created_at  timestamptz not null default now()
);

create table if not exists ops.cities (
  id          uuid primary key default gen_random_uuid(),
  country_id  uuid not null references ops.countries (id) on delete cascade,
  name_en     text not null,
  name_ar     text not null default '',
  created_at  timestamptz not null default now()
);

create table if not exists ops.professions (
  id          uuid primary key default gen_random_uuid(),
  name_en     text not null,
  name_ar     text not null default '',
  created_at  timestamptz not null default now()
);

create table if not exists ops.payment_sources (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  -- 'Invoices' and/or 'Request Status'
  scopes      text[] not null default '{}',
  created_at  timestamptz not null default now()
);

-- One row, enforced by the check constraint.
create table if not exists ops.settings (
  id              boolean primary key default true check (id),
  company_name    text not null default 'Eleutheria',
  company_tagline text not null default 'International Placement Services',
  license_number  text not null default '',
  address         text not null default '',
  currency        text not null default 'USD',
  updated_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------- people --

-- An account. `user_id` is the Supabase auth user; a row without one is a
-- person on the payroll who cannot sign in. The role here is the same role the
-- interface uses, and from now on it is the database that enforces it.
create table if not exists ops.staff (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid unique,
  username    text not null unique check (username = lower(username)),
  name_en     text not null,
  name_ar     text not null default '',
  phone       text not null default '',
  email       text not null default '',
  role        text not null default 'data_entry'
                check (role in ('admin', 'accountant', 'data_entry')),
  status      text not null default 'Active'
                check (status in ('Active', 'Inactive', 'Suspended')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on column ops.staff.user_id is
  'The Supabase auth user. Passwords live in auth.users and never here.';

-- The partner office abroad that a domestic worker comes through.
create table if not exists ops.agencies (
  id                   uuid primary key default gen_random_uuid(),
  english_name         text not null,
  arabic_name          text not null default '',
  license_number       text not null default '',
  license_expiry       date,
  phone                text not null default '',
  email                text not null default '',
  telephone            text not null default '',
  rating               smallint not null default 0 check (rating between 0 and 5),
  primary_manager_en   text not null default '',
  primary_manager_ar   text not null default '',
  second_manager_en    text not null default '',
  second_manager_ar    text not null default '',
  status               text not null default 'Active' check (status in ('Active', 'Inactive')),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

-- A person who introduces candidates one at a time and earns on each one that
-- gets through.
create table if not exists ops.agents (
  id              uuid primary key default gen_random_uuid(),
  name_en         text not null,
  name_ar         text not null default '',
  phone           text not null default '',
  email           text not null default '',
  area            text not null default '',
  status          text not null default 'Active' check (status in ('Active', 'Inactive')),
  selection_fee   numeric(12,2) not null default 0 check (selection_fee >= 0),
  deployment_fee  numeric(12,2) not null default 0 check (deployment_fee >= 0),
  notes           text not null default '',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists ops.employers (
  id                          uuid primary key default gen_random_uuid(),
  english_name                text not null,
  arabic_name                 text not null default '',
  email                       text not null default '',
  phone                       text not null default '',
  telephone                   text not null default '',
  national_address            text not null default '',
  national_id_number          text not null default '',
  national_address_short_code text not null default '',
  profile_image_path          text,
  status                      text not null default 'Active' check (status in ('Active', 'Inactive')),
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now()
);

-- Passport and identity numbers live here and are never exposed publicly.
-- See the published_workers view in 0002_security.sql.
create table if not exists ops.applicants (
  id                     uuid primary key default gen_random_uuid(),
  english_name           text not null,
  arabic_name            text not null default '',
  gender                 text not null check (gender in ('Male', 'Female')),
  dob                    date,
  country                text not null default '',
  profession             text not null default '',
  type                   text not null default 'Domestic' check (type in ('Domestic', 'Profession')),
  experience_years       smallint not null default 0,
  passport_no            text not null default '',
  passport_start         date,
  passport_end           date,
  id_number              text not null default '',
  phone                  text not null default '',
  telephone              text not null default '',
  status                 text not null default 'Available'
                           check (status in ('Available', 'Unavailable', 'Selected', 'Deployed', 'Back Out')),
  photo_path             text,
  cv_path                text,
  -- The name the office uploaded, beside the uuid the file is stored under.
  cv_file_name           text,
  passport_copy_path     text,
  -- The switch that decides whether this worker appears on the public site.
  published_to_website   boolean not null default false,
  agency_id              uuid references ops.agencies (id) on delete set null,
  agent_id               uuid references ops.agents (id) on delete set null,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  updated_by             uuid references ops.staff (id) on delete set null
);

create table if not exists ops.applicant_experience (
  id            uuid primary key default gen_random_uuid(),
  applicant_id  uuid not null references ops.applicants (id) on delete cascade,
  title         text not null,
  employer      text not null default '',
  years         smallint not null default 0
);

create table if not exists ops.applicant_education (
  id            uuid primary key default gen_random_uuid(),
  applicant_id  uuid not null references ops.applicants (id) on delete cascade,
  degree        text not null,
  institution   text not null default '',
  year          text not null default ''
);

create table if not exists ops.applicant_documents (
  id            uuid primary key default gen_random_uuid(),
  applicant_id  uuid not null references ops.applicants (id) on delete cascade,
  name          text not null,
  category      text not null default '',
  storage_path  text,
  uploaded_at   timestamptz not null default now()
);

create table if not exists ops.applicant_notes (
  id            uuid primary key default gen_random_uuid(),
  applicant_id  uuid not null references ops.applicants (id) on delete cascade,
  author_id     uuid references ops.staff (id) on delete set null,
  body          text not null,
  created_at    timestamptz not null default now()
);

-- ------------------------------------------------------------ placements --

create table if not exists ops.requests (
  id                       uuid primary key default gen_random_uuid(),
  type                     text not null check (type in ('Domestic', 'Profession')),
  contract_duration_months smallint not null default 24,
  applicant_id             uuid not null references ops.applicants (id) on delete restrict,
  employer_id              uuid not null references ops.employers (id) on delete restrict,
  responsible_staff_id     uuid references ops.staff (id) on delete set null,
  agency_id                uuid references ops.agencies (id) on delete set null,
  mosaned_number           text not null default '',
  notes_en                 text not null default '',
  notes_ar                 text not null default '',
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

-- The stage log. Reaching a stage is what creates an agent's commission, a
-- partner office's charge and a backout, so this table is the origin of most
-- of the money below it.
create table if not exists ops.request_status_history (
  id                    uuid primary key default gen_random_uuid(),
  request_id            uuid not null references ops.requests (id) on delete cascade,
  status                text not null,
  occurred_on           date not null,
  cost                  numeric(12,2) not null default 0 check (cost >= 0),
  payment_source_id     uuid references ops.payment_sources (id) on delete set null,
  responsible_staff_id  uuid references ops.staff (id) on delete set null,
  attachment_path       text,
  attachment_name       text,
  attachment_type       text,
  attachment_size       integer,
  notes                 text not null default '',
  created_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------- money ---

create table if not exists ops.invoices (
  id             uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  request_id     uuid references ops.requests (id) on delete set null,
  employer_id    uuid not null references ops.employers (id) on delete restrict,
  agency_id      uuid references ops.agencies (id) on delete set null,
  service_price  numeric(12,2) not null check (service_price >= 0),
  status         text not null default 'Issued'
                   check (status in ('Issued', 'Partial Payment', 'Completed')),
  issued_on      date not null default current_date,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists ops.invoice_payments (
  id                uuid primary key default gen_random_uuid(),
  invoice_id        uuid not null references ops.invoices (id) on delete cascade,
  paid_on           date not null,
  amount            numeric(12,2) not null check (amount > 0),
  payment_source_id uuid references ops.payment_sources (id) on delete set null,
  attachment_path   text,
  attachment_name   text,
  attachment_type   text,
  attachment_size   integer,
  created_at        timestamptz not null default now()
);

create table if not exists ops.payroll_entries (
  id              uuid primary key default gen_random_uuid(),
  staff_id        uuid not null references ops.staff (id) on delete cascade,
  -- First day of the month the entry covers.
  period          date not null,
  basic_salary    numeric(12,2) not null default 0 check (basic_salary >= 0),
  overtime        numeric(12,2) not null default 0 check (overtime >= 0),
  allowances      numeric(12,2) not null default 0 check (allowances >= 0),
  status          text not null default 'Pending' check (status in ('Paid', 'Pending')),
  attachment_path text,
  attachment_name text,
  attachment_type text,
  attachment_size integer,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (staff_id, period)
);

create table if not exists ops.office_expenses (
  id              uuid primary key default gen_random_uuid(),
  item_en         text not null,
  item_ar         text not null default '',
  category        text not null default '',
  amount          numeric(12,2) not null check (amount >= 0),
  spent_on        date not null,
  status          text not null default 'Paid' check (status in ('Paid', 'Pending')),
  attachment_path text,
  attachment_name text,
  attachment_type text,
  attachment_size integer,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- What a partner office pays for each domestic worker placed with them.
create table if not exists ops.agency_contracts (
  id               uuid primary key default gen_random_uuid(),
  agency_id        uuid not null references ops.agencies (id) on delete cascade,
  reference        text not null default '',
  price_per_worker numeric(12,2) not null check (price_per_worker >= 0),
  signed_on        date,
  expires_on       date,
  status           text not null default 'Active' check (status in ('Active', 'Expired')),
  notes            text not null default '',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- Half of that price falls due at selection, half when the visa is issued.
-- One row per request and milestone, which is what makes the app's re-sync
-- idempotent.
create table if not exists ops.agency_charges (
  id                uuid primary key default gen_random_uuid(),
  agency_id         uuid not null references ops.agencies (id) on delete cascade,
  contract_id       uuid references ops.agency_contracts (id) on delete set null,
  applicant_id      uuid not null references ops.applicants (id) on delete cascade,
  request_id        uuid not null references ops.requests (id) on delete cascade,
  milestone         text not null check (milestone in ('Selected', 'Visa Issued')),
  amount            numeric(12,2) not null check (amount >= 0),
  due_on            date not null,
  status            text not null default 'Pending' check (status in ('Pending', 'Paid')),
  settled_on        date,
  payment_source_id uuid references ops.payment_sources (id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (request_id, milestone)
);

-- Half an agent's fee at selection, the other half at deployment.
create table if not exists ops.agent_commissions (
  id                uuid primary key default gen_random_uuid(),
  agent_id          uuid not null references ops.agents (id) on delete cascade,
  applicant_id      uuid not null references ops.applicants (id) on delete cascade,
  request_id        uuid not null references ops.requests (id) on delete cascade,
  milestone         text not null check (milestone in ('Selected', 'Deployed')),
  amount            numeric(12,2) not null check (amount >= 0),
  earned_on         date not null,
  status            text not null default 'Pending' check (status in ('Pending', 'Paid')),
  paid_on           date,
  payment_source_id uuid references ops.payment_sources (id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (request_id, milestone)
);

-- A worker who pulled out. Inside the guarantee window the company brings her
-- home at its own expense, which is what backout_costs records.
create table if not exists ops.backouts (
  id            uuid primary key default gen_random_uuid(),
  request_id    uuid not null references ops.requests (id) on delete cascade unique,
  applicant_id  uuid not null references ops.applicants (id) on delete cascade,
  deployed_on   date,
  returned_on   date not null,
  reason        text not null default '',
  liability     text not null default 'Company'
                  check (liability in ('Company', 'Employer', 'Agency')),
  notes         text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists ops.backout_costs (
  id                uuid primary key default gen_random_uuid(),
  backout_id        uuid not null references ops.backouts (id) on delete cascade,
  label_en          text not null,
  label_ar          text not null default '',
  category          text not null default '',
  amount            numeric(12,2) not null check (amount >= 0),
  spent_on          date not null,
  status            text not null default 'Pending' check (status in ('Pending', 'Paid')),
  payment_source_id uuid references ops.payment_sources (id) on delete set null,
  attachment_path   text,
  attachment_name   text,
  attachment_type   text,
  attachment_size   integer,
  created_at        timestamptz not null default now()
);

-- ------------------------------------------------------------- personal ---

create table if not exists ops.notifications (
  id          uuid primary key default gen_random_uuid(),
  staff_id    uuid references ops.staff (id) on delete cascade,
  title       text not null,
  detail      text not null default '',
  read_at     timestamptz,
  created_at  timestamptz not null default now()
);

-- -------------------------------------------------------------- indexes ---

create index if not exists ops_cities_country_id_idx on ops.cities (country_id);
create index if not exists ops_applicants_agency_id_idx on ops.applicants (agency_id);
create index if not exists ops_applicants_agent_id_idx on ops.applicants (agent_id);
create index if not exists ops_applicants_status_idx on ops.applicants (status);
create index if not exists ops_applicants_published_to_website_partial_idx on ops.applicants (published_to_website) where published_to_website;
create index if not exists ops_applicant_experience_applicant_id_idx on ops.applicant_experience (applicant_id);
create index if not exists ops_applicant_education_applicant_id_idx on ops.applicant_education (applicant_id);
create index if not exists ops_applicant_documents_applicant_id_idx on ops.applicant_documents (applicant_id);
create index if not exists ops_applicant_notes_applicant_id_idx on ops.applicant_notes (applicant_id);
create index if not exists ops_requests_applicant_id_idx on ops.requests (applicant_id);
create index if not exists ops_requests_employer_id_idx on ops.requests (employer_id);
create index if not exists ops_requests_agency_id_idx on ops.requests (agency_id);
create index if not exists ops_request_status_history_request_id_occurred_on_idx on ops.request_status_history (request_id, occurred_on);
create index if not exists ops_invoices_employer_id_idx on ops.invoices (employer_id);
create index if not exists ops_invoices_agency_id_idx on ops.invoices (agency_id);
create index if not exists ops_invoice_payments_invoice_id_idx on ops.invoice_payments (invoice_id);
create index if not exists ops_payroll_entries_period_idx on ops.payroll_entries (period);
create index if not exists ops_office_expenses_spent_on_idx on ops.office_expenses (spent_on);
create index if not exists ops_agency_contracts_agency_id_idx on ops.agency_contracts (agency_id);
create index if not exists ops_agency_charges_agency_id_status_idx on ops.agency_charges (agency_id, status);
create index if not exists ops_agent_commissions_agent_id_status_idx on ops.agent_commissions (agent_id, status);
create index if not exists ops_backout_costs_backout_id_idx on ops.backout_costs (backout_id);
create index if not exists ops_notifications_staff_id_read_at_idx on ops.notifications (staff_id, read_at);

-- ------------------------------------------------------------- triggers ---

drop trigger if exists staff_updated on ops.staff;
create trigger staff_updated before update on ops.staff for each row execute function ops.set_updated_at();
drop trigger if exists agencies_updated on ops.agencies;
create trigger agencies_updated before update on ops.agencies for each row execute function ops.set_updated_at();
drop trigger if exists agents_updated on ops.agents;
create trigger agents_updated before update on ops.agents for each row execute function ops.set_updated_at();
drop trigger if exists employers_updated on ops.employers;
create trigger employers_updated before update on ops.employers for each row execute function ops.set_updated_at();
drop trigger if exists applicants_updated on ops.applicants;
create trigger applicants_updated before update on ops.applicants for each row execute function ops.set_updated_at();
drop trigger if exists requests_updated on ops.requests;
create trigger requests_updated before update on ops.requests for each row execute function ops.set_updated_at();
drop trigger if exists invoices_updated on ops.invoices;
create trigger invoices_updated before update on ops.invoices for each row execute function ops.set_updated_at();
drop trigger if exists payroll_updated on ops.payroll_entries;
create trigger payroll_updated before update on ops.payroll_entries for each row execute function ops.set_updated_at();
drop trigger if exists office_exp_updated on ops.office_expenses;
create trigger office_exp_updated before update on ops.office_expenses for each row execute function ops.set_updated_at();
drop trigger if exists contracts_updated on ops.agency_contracts;
create trigger contracts_updated before update on ops.agency_contracts for each row execute function ops.set_updated_at();
drop trigger if exists charges_updated on ops.agency_charges;
create trigger charges_updated before update on ops.agency_charges for each row execute function ops.set_updated_at();
drop trigger if exists commissions_updated on ops.agent_commissions;
create trigger commissions_updated before update on ops.agent_commissions for each row execute function ops.set_updated_at();
drop trigger if exists backouts_updated on ops.backouts;
create trigger backouts_updated before update on ops.backouts for each row execute function ops.set_updated_at();
drop trigger if exists settings_updated on ops.settings;
create trigger settings_updated before update on ops.settings for each row execute function ops.set_updated_at();


-- ======================================================== 0002_security.sql --

-- Who can read and write what.
--
-- The application already sorts every screen and every action into an area --
-- finance, operations, system, personal -- and gives each role a list it may
-- read and a list it may change. Until now those rules lived only in the
-- browser, where anyone who opens the developer tools can edit them. Here they
-- become the database's rules, which is the real point of the move:
--
--   admin       reads and writes everything
--   accountant  writes finance, reads operations and the reference data
--   data_entry  writes operations, and cannot read finance at all
--   anon        reads one view of published workers, and nothing else
--
-- Every table is locked by default. Nothing is readable without a policy.

-- ------------------------------------------------------------- who am i ---

-- The signed-in caller's role, or null when they are not active staff.
-- security definer so it can read ops.staff while ops.staff is itself locked.
create or replace function ops.current_role() returns text
language sql stable security definer set search_path = ops, pg_temp as $$
  select role from ops.staff where user_id = auth.uid() and status = 'Active';
$$;

create or replace function ops.is_staff() returns boolean
language sql stable as $$ select ops.current_role() is not null $$;

create or replace function ops.is_admin() returns boolean
language sql stable as $$ select ops.current_role() = 'admin' $$;

-- Reading the money: the accountant's job, and the administrator's.
create or replace function ops.can_read_finance() returns boolean
language sql stable as $$ select ops.current_role() in ('admin', 'accountant') $$;

create or replace function ops.can_write_finance() returns boolean
language sql stable as $$ select ops.current_role() in ('admin', 'accountant') $$;

-- Working the caseload: data entry's job, and the administrator's. An
-- accountant reads it -- the money makes no sense without it -- but does not
-- change it.
create or replace function ops.can_write_operations() returns boolean
language sql stable as $$ select ops.current_role() in ('admin', 'data_entry') $$;

-- --------------------------------------------------------------- grants ---

-- PostgREST reaches the schema through these roles; RLS below decides the
-- rest. `anon` is given nothing here on purpose: the website's key can see the
-- published_workers view at the bottom of this file and not one row more.
grant usage on schema ops to authenticated;
grant select, insert, update, delete on all tables in schema ops to authenticated;
alter default privileges in schema ops grant select, insert, update, delete on tables to authenticated;

-- --------------------------------------------------------- lock it all ----

do $$
declare t text;
begin
  for t in select tablename from pg_tables where schemaname = 'ops'
  loop
    execute format('alter table ops.%I enable row level security', t);
    execute format('alter table ops.%I force row level security', t);
  end loop;
end
$$;

-- ---------------------------------------------------------- the policies --

-- Reference data and the staff list: everyone signed in needs to read these to
-- fill a dropdown or name the person who handled a request. Only an
-- administrator changes them.
do $$
declare t text;
begin
  foreach t in array array['countries', 'cities', 'professions', 'payment_sources', 'staff', 'settings']
  loop
    execute format('drop policy if exists read_all_staff on ops.%I', t);
    execute format('drop policy if exists write_admin on ops.%I', t);
    execute format('drop policy if exists update_admin on ops.%I', t);
    execute format('drop policy if exists delete_admin on ops.%I', t);
    execute format('create policy read_all_staff on ops.%I for select to authenticated using (ops.is_staff())', t);
    execute format('create policy write_admin on ops.%I for insert to authenticated with check (ops.is_admin())', t);
    execute format('create policy update_admin on ops.%I for update to authenticated using (ops.is_admin()) with check (ops.is_admin())', t);
    execute format('create policy delete_admin on ops.%I for delete to authenticated using (ops.is_admin())', t);
  end loop;
end
$$;

-- The caseload.
do $$
declare t text;
begin
  foreach t in array array[
    'employers', 'agencies', 'agents', 'applicants', 'applicant_experience',
    'applicant_education', 'applicant_documents', 'applicant_notes',
    'requests', 'request_status_history'
  ]
  loop
    execute format('drop policy if exists read_all_staff on ops.%I', t);
    execute format('drop policy if exists write_operations on ops.%I', t);
    execute format('drop policy if exists update_operations on ops.%I', t);
    execute format('drop policy if exists delete_operations on ops.%I', t);
    execute format('create policy read_all_staff on ops.%I for select to authenticated using (ops.is_staff())', t);
    execute format('create policy write_operations on ops.%I for insert to authenticated with check (ops.can_write_operations())', t);
    execute format('create policy update_operations on ops.%I for update to authenticated using (ops.can_write_operations()) with check (ops.can_write_operations())', t);
    execute format('create policy delete_operations on ops.%I for delete to authenticated using (ops.can_write_operations())', t);
  end loop;
end
$$;

-- The money. Data entry cannot even read these, which is what the finance
-- pages being absent from their sidebar has meant all along.
do $$
declare t text;
begin
  foreach t in array array[
    'invoices', 'invoice_payments', 'payroll_entries', 'office_expenses',
    'agency_contracts', 'agency_charges', 'agent_commissions',
    'backouts', 'backout_costs'
  ]
  loop
    execute format('drop policy if exists read_finance on ops.%I', t);
    execute format('drop policy if exists write_finance on ops.%I', t);
    execute format('drop policy if exists update_finance on ops.%I', t);
    execute format('drop policy if exists delete_finance on ops.%I', t);
    execute format('create policy read_finance on ops.%I for select to authenticated using (ops.can_read_finance())', t);
    execute format('create policy write_finance on ops.%I for insert to authenticated with check (ops.can_write_finance())', t);
    execute format('create policy update_finance on ops.%I for update to authenticated using (ops.can_write_finance()) with check (ops.can_write_finance())', t);
    execute format('create policy delete_finance on ops.%I for delete to authenticated using (ops.can_write_finance())', t);
  end loop;
end
$$;

-- Payroll is what colleagues earn, so it is the administrator's alone --
-- narrower than the rest of finance, and deliberately so.
drop policy if exists read_finance   on ops.payroll_entries;
drop policy if exists write_finance  on ops.payroll_entries;
drop policy if exists update_finance on ops.payroll_entries;
drop policy if exists delete_finance on ops.payroll_entries;
drop policy if exists read_admin     on ops.payroll_entries;
drop policy if exists write_admin    on ops.payroll_entries;
drop policy if exists update_admin   on ops.payroll_entries;
drop policy if exists delete_admin   on ops.payroll_entries;
create policy read_admin   on ops.payroll_entries for select to authenticated using (ops.is_admin());
create policy write_admin  on ops.payroll_entries for insert to authenticated with check (ops.is_admin());
create policy update_admin on ops.payroll_entries for update to authenticated using (ops.is_admin()) with check (ops.is_admin());
create policy delete_admin on ops.payroll_entries for delete to authenticated using (ops.is_admin());

-- A notice addressed to somebody is theirs; one addressed to nobody is for the
-- whole office.
drop policy if exists read_own on ops.notifications;
create policy read_own on ops.notifications for select to authenticated
  using (ops.is_staff() and (staff_id is null or staff_id in (select id from ops.staff where user_id = auth.uid())));
drop policy if exists write_own on ops.notifications;
create policy write_own on ops.notifications for insert to authenticated
  with check (ops.is_staff());
drop policy if exists update_own on ops.notifications;
create policy update_own on ops.notifications for update to authenticated
  using (ops.is_staff() and (staff_id is null or staff_id in (select id from ops.staff where user_id = auth.uid())))
  with check (ops.is_staff());
drop policy if exists delete_own on ops.notifications;
create policy delete_own on ops.notifications for delete to authenticated
  using (ops.is_staff() and (staff_id is null or staff_id in (select id from ops.staff where user_id = auth.uid())));

-- Nobody may hand themselves a role or reactivate their own suspended account,
-- administrator or not: that is the one edit that could quietly undo all of
-- the above.
create or replace function ops.guard_own_account() returns trigger
language plpgsql security definer set search_path = ops, pg_temp as $$
begin
  if new.user_id is not distinct from auth.uid()
     and (new.role is distinct from old.role or new.status is distinct from old.status) then
    raise exception 'You cannot change your own role or status.';
  end if;
  return new;
end;
$$;

drop trigger if exists staff_guard_self on ops.staff;
create trigger staff_guard_self before update on ops.staff
  for each row execute function ops.guard_own_account();

-- --------------------------------------------------- the public website ---

-- The projection the website reads lives in 0007_public_projection.sql, which
-- owns all of it: the function that does the reading, the view over it, and
-- the one policy that lets it through. It is kept in one file because those
-- three pieces only make sense together, and splitting them was how a single
-- well-meant change in the Supabase dashboard took the website down.



-- ======================================================== 0003_storage.sql --

-- File storage.
--
-- Three private buckets, because none of what they hold is public:
--
--   worker-photos     the photograph on a worker's profile
--   worker-documents  CVs, passport copies, anything attached to an applicant
--   bills             the receipt behind a payment, an expense or a backout
--
-- The website shows photographs of published workers, but it does so by asking
-- its own server for a signed URL, which keeps every unpublished worker's
-- photograph out of reach. A public bucket would publish all of them.
--
-- Run this after creating the three buckets in Storage, or let the inserts
-- below create them.

insert into storage.buckets (id, name, public)
values
  ('worker-photos', 'worker-photos', false),
  ('worker-documents', 'worker-documents', false),
  ('bills', 'bills', false)
on conflict (id) do nothing;

-- Staff read and write; nobody else reaches the buckets at all. Who may see a
-- bill is decided by the table that points at it, which is already locked to
-- the roles that may read finance.
do $$
declare b text;
begin
  foreach b in array array['worker-photos', 'worker-documents', 'bills']
  loop
    execute format('drop policy if exists %I on storage.objects', b || '_read');
    execute format('drop policy if exists %I on storage.objects', b || '_write');
    execute format('drop policy if exists %I on storage.objects', b || '_update');
    execute format('drop policy if exists %I on storage.objects', b || '_delete');
    execute format(
      'create policy %I on storage.objects for select to authenticated using (bucket_id = %L and ops.is_staff())',
      b || '_read', b);
    execute format(
      'create policy %I on storage.objects for insert to authenticated with check (bucket_id = %L and ops.is_staff())',
      b || '_write', b);
    execute format(
      'create policy %I on storage.objects for update to authenticated using (bucket_id = %L and ops.is_staff()) with check (bucket_id = %L and ops.is_staff())',
      b || '_update', b, b);
    execute format(
      'create policy %I on storage.objects for delete to authenticated using (bucket_id = %L and ops.is_staff())',
      b || '_delete', b);
  end loop;
end
$$;


-- ======================================================== 0004_derived_billing.sql --

-- The money the stage log creates, created by the database.
--
-- An agent earns half their fee when their candidate is selected and the other
-- half when she is deployed. A partner office owes half its contract price at
-- selection and the other half when the visa is issued. A worker who pulls out
-- opens a backout. None of that is typed in: it follows from the stage log.
--
-- The app has worked this out in the browser until now. That stops here, for a
-- reason that only appears once the roles are real: data entry may log a stage
-- but may not read finance, so a browser that cannot see a commission cannot
-- maintain one either. Deriving it here means it happens whoever logs the
-- stage, and there is one copy of the rule rather than one per client.
--
-- Two things this must never do, the same two the application never did:
--   * change or remove a row whose money has already moved
--   * invent a row for a stage that has not happened
--
-- Mirrors src/lib/derivedBilling.ts and src/data/businessRules.ts.

-- A worker who leaves before this many months is brought home at our expense.
create or replace function ops.guarantee_months() returns integer
language sql immutable as $$ select 3 $$;

create or replace function ops.months_between(from_date date, to_date date)
returns integer language sql immutable as $$
  select greatest(0, (extract(year from age(to_date, from_date)) * 12
                    + extract(month from age(to_date, from_date)))::int)
$$;

create or replace function ops.sync_derived_billing(p_request uuid) returns void
language plpgsql security definer set search_path = ops, pg_temp as $$
declare
  the_request   ops.requests%rowtype;
  the_applicant ops.applicants%rowtype;
  the_agent     ops.agents%rowtype;
  the_contract  ops.agency_contracts%rowtype;
  half          numeric(12,2);
  on_selected   date;
  on_deployed   date;
  on_visa       date;
  on_backout    date;
  liability     text;
begin
  select * into the_request from ops.requests where id = p_request;
  if not found then return; end if;
  select * into the_applicant from ops.applicants where id = the_request.applicant_id;
  if not found then return; end if;

  -- The latest date each milestone was logged on, or null if it never was.
  select max(occurred_on) into on_selected
    from ops.request_status_history where request_id = p_request and status = 'Selected';
  select max(occurred_on) into on_deployed
    from ops.request_status_history where request_id = p_request and status = 'Deployed';
  select max(occurred_on) into on_visa
    from ops.request_status_history where request_id = p_request and status = 'Visa Stamping';
  select max(occurred_on) into on_backout
    from ops.request_status_history where request_id = p_request and status = 'Back Out';

  -- ---------------------------------------------------- the agent's halves --
  select * into the_agent from ops.agents where id = the_applicant.agent_id;

  if found and on_selected is not null then
    insert into ops.agent_commissions (agent_id, applicant_id, request_id, milestone, amount, earned_on)
    values (the_agent.id, the_applicant.id, p_request, 'Selected', the_agent.selection_fee, on_selected)
    on conflict (request_id, milestone) do update
       set agent_id = excluded.agent_id,
           applicant_id = excluded.applicant_id,
           amount = excluded.amount,
           earned_on = excluded.earned_on
     where ops.agent_commissions.status = 'Pending';
  else
    delete from ops.agent_commissions
     where request_id = p_request and milestone = 'Selected' and status = 'Pending';
  end if;

  if the_agent.id is not null and on_deployed is not null then
    insert into ops.agent_commissions (agent_id, applicant_id, request_id, milestone, amount, earned_on)
    values (the_agent.id, the_applicant.id, p_request, 'Deployed', the_agent.deployment_fee, on_deployed)
    on conflict (request_id, milestone) do update
       set agent_id = excluded.agent_id,
           applicant_id = excluded.applicant_id,
           amount = excluded.amount,
           earned_on = excluded.earned_on
     where ops.agent_commissions.status = 'Pending';
  else
    delete from ops.agent_commissions
     where request_id = p_request and milestone = 'Deployed' and status = 'Pending';
  end if;

  -- ------------------------------------------- the partner office's halves --
  -- A contract prices a domestic worker. A tradesman placed through the same
  -- office is not covered by it, and must not be billed at that price.
  if the_request.type = 'Domestic' then
    select * into the_contract
      from ops.agency_contracts
     where agency_id = the_request.agency_id
     order by (status = 'Active') desc, signed_on desc nulls last
     limit 1;
  end if;
  half := round(coalesce(the_contract.price_per_worker, 0) / 2, 2);

  if the_contract.id is not null and on_selected is not null then
    insert into ops.agency_charges (agency_id, contract_id, applicant_id, request_id, milestone, amount, due_on)
    values (the_contract.agency_id, the_contract.id, the_applicant.id, p_request, 'Selected', half, on_selected)
    on conflict (request_id, milestone) do update
       set agency_id = excluded.agency_id,
           contract_id = excluded.contract_id,
           applicant_id = excluded.applicant_id,
           amount = excluded.amount,
           due_on = excluded.due_on
     where ops.agency_charges.status = 'Pending';
  else
    delete from ops.agency_charges
     where request_id = p_request and milestone = 'Selected' and status = 'Pending';
  end if;

  if the_contract.id is not null and on_visa is not null then
    insert into ops.agency_charges (agency_id, contract_id, applicant_id, request_id, milestone, amount, due_on)
    values (the_contract.agency_id, the_contract.id, the_applicant.id, p_request, 'Visa Issued', half, on_visa)
    on conflict (request_id, milestone) do update
       set agency_id = excluded.agency_id,
           contract_id = excluded.contract_id,
           applicant_id = excluded.applicant_id,
           amount = excluded.amount,
           due_on = excluded.due_on
     where ops.agency_charges.status = 'Pending';
  else
    delete from ops.agency_charges
     where request_id = p_request and milestone = 'Visa Issued' and status = 'Pending';
  end if;

  -- ------------------------------------------------------------- backouts --
  if on_backout is not null then
    -- Deployment only counts if it came first; she can also walk away
    -- mid-pipeline, and what was spent on her is just as real.
    if on_deployed is null or on_deployed > on_backout then
      on_deployed := null;
    end if;

    liability := case
      when on_deployed is null then 'Company'
      when ops.months_between(on_deployed, on_backout) < ops.guarantee_months() then 'Company'
      else 'Employer'
    end;

    insert into ops.backouts (request_id, applicant_id, deployed_on, returned_on, liability)
    values (p_request, the_applicant.id, on_deployed, on_backout, liability)
    on conflict (request_id) do update
       set applicant_id = excluded.applicant_id,
           deployed_on = excluded.deployed_on,
           returned_on = excluded.returned_on,
           -- An office that decided the agency carries it has decided.
           liability = case when ops.backouts.liability = 'Agency' then 'Agency' else excluded.liability end;
  else
    -- Only while nothing has been spent on bringing her home: a bill is a
    -- record, not a toggle.
    delete from ops.backouts b
     where b.request_id = p_request
       and not exists (select 1 from ops.backout_costs c where c.backout_id = b.id);
  end if;
end;
$$;

-- --------------------------------------------------------------- triggers --

-- The stage log is the origin of all of it.
create or replace function ops.on_status_history_change() returns trigger
language plpgsql security definer set search_path = ops, pg_temp as $$
begin
  perform ops.sync_derived_billing(coalesce(new.request_id, old.request_id));
  return null;
end;
$$;

drop trigger if exists status_history_derives_billing on ops.request_status_history;
create trigger status_history_derives_billing
  after insert or update or delete on ops.request_status_history
  for each row execute function ops.on_status_history_change();

-- Attaching or detaching an agent changes who is owed for every request of
-- hers; so does moving a worker to another partner office.
create or replace function ops.on_applicant_change() returns trigger
language plpgsql security definer set search_path = ops, pg_temp as $$
declare r uuid;
begin
  if new.agent_id is distinct from old.agent_id or new.agency_id is distinct from old.agency_id then
    for r in select id from ops.requests where applicant_id = new.id loop
      perform ops.sync_derived_billing(r);
    end loop;
  end if;
  return null;
end;
$$;

drop trigger if exists applicant_derives_billing on ops.applicants;
create trigger applicant_derives_billing
  after update on ops.applicants
  for each row execute function ops.on_applicant_change();

-- A changed fee or contract price moves every unsettled amount that came from
-- it. One function per table: `new` is a different row type in each, and a
-- single function referring to a column only one of them has fails the moment
-- it runs.
create or replace function ops.on_agent_terms_change() returns trigger
language plpgsql security definer set search_path = ops, pg_temp as $$
declare r uuid;
begin
  if new.selection_fee is distinct from old.selection_fee
     or new.deployment_fee is distinct from old.deployment_fee then
    for r in
      select req.id from ops.requests req
        join ops.applicants a on a.id = req.applicant_id
       where a.agent_id = new.id
    loop
      perform ops.sync_derived_billing(r);
    end loop;
  end if;
  return null;
end;
$$;

drop trigger if exists agent_terms_derive_billing on ops.agents;
create trigger agent_terms_derive_billing
  after update on ops.agents
  for each row execute function ops.on_agent_terms_change();

create or replace function ops.on_contract_change() returns trigger
language plpgsql security definer set search_path = ops, pg_temp as $$
declare r uuid;
begin
  for r in select id from ops.requests where agency_id = new.agency_id loop
    perform ops.sync_derived_billing(r);
  end loop;
  return null;
end;
$$;

drop trigger if exists contract_terms_derive_billing on ops.agency_contracts;
create trigger contract_terms_derive_billing
  after insert or update on ops.agency_contracts
  for each row execute function ops.on_contract_change();

-- Rebuilds everything from the stage log. Run it once after an import, or any
-- time you want to be sure the books agree with the history.
create or replace function ops.rebuild_derived_billing() returns integer
language plpgsql security definer set search_path = ops, pg_temp as $$
declare r uuid; n integer := 0;
begin
  for r in select id from ops.requests loop
    perform ops.sync_derived_billing(r);
    n := n + 1;
  end loop;
  return n;
end;
$$;


-- ======================================================== 0005_published_photos.sql --

-- Photographs of the workers who are on the website.
--
-- worker-photos is private and holds every applicant's photograph. That is
-- right for a file about somebody who has not been published anywhere, and
-- wrong for the website, whose visitors have no account and no key.
--
-- So there are two buckets. A photograph is copied into the public one when
-- somebody deliberately publishes that worker, and removed from it the moment
-- they stop. What is publicly readable is then exactly what somebody chose to
-- publish, rather than everything that happens to have been uploaded.
--
-- The object keeps the same key in both, so the view's photo_path is all the
-- website needs:
--
--   https://<project>.supabase.co/storage/v1/object/public/published-photos/<photo_path>

insert into storage.buckets (id, name, public)
values ('published-photos', 'published-photos', true)
on conflict (id) do update set public = true;

-- Staff put photographs here and take them away; everyone may look.
do $$
begin
  execute 'drop policy if exists published_photos_read on storage.objects';
  execute 'drop policy if exists published_photos_write on storage.objects';
  execute 'drop policy if exists published_photos_update on storage.objects';
  execute 'drop policy if exists published_photos_delete on storage.objects';

  execute $p$create policy published_photos_read on storage.objects
    for select to anon, authenticated using (bucket_id = 'published-photos')$p$;
  execute $p$create policy published_photos_write on storage.objects
    for insert to authenticated with check (bucket_id = 'published-photos' and ops.is_staff())$p$;
  execute $p$create policy published_photos_update on storage.objects
    for update to authenticated using (bucket_id = 'published-photos' and ops.is_staff())
    with check (bucket_id = 'published-photos' and ops.is_staff())$p$;
  execute $p$create policy published_photos_delete on storage.objects
    for delete to authenticated using (bucket_id = 'published-photos' and ops.is_staff())$p$;
end
$$;


-- ======================================================== 0006_published_cvs.sql --

-- The CV a visitor to the website can read.
--
-- A photograph tells somebody almost nothing; the CV is what they actually
-- want, and until now it was only ever a file name on the record. So a CV is
-- now a file like the photograph is, kept in the private worker-documents
-- bucket, copied into a public one when the worker is published, and removed
-- from it the moment she is not.
--
--   https://<project>.supabase.co/storage/v1/object/public/published-cvs/<cv_path>
--
-- What this means is worth saying plainly: a published CV is readable by
-- anyone who has its address, with no key and no sign-in, for as long as the
-- worker is on the website. That is what putting a CV on a public site is.
-- Keep passport scans and identity papers out of the file, and unpublish a
-- worker to withdraw hers.

-- The file name is kept beside the path, because a path is a uuid and the
-- office needs to see the document it uploaded.
alter table ops.applicants add column if not exists cv_file_name text;

insert into storage.buckets (id, name, public)
values ('published-cvs', 'published-cvs', true)
on conflict (id) do update set public = true;

do $$
begin
  execute 'drop policy if exists published_cvs_read on storage.objects';
  execute 'drop policy if exists published_cvs_write on storage.objects';
  execute 'drop policy if exists published_cvs_update on storage.objects';
  execute 'drop policy if exists published_cvs_delete on storage.objects';

  execute $p$create policy published_cvs_read on storage.objects
    for select to anon, authenticated using (bucket_id = 'published-cvs')$p$;
  execute $p$create policy published_cvs_write on storage.objects
    for insert to authenticated with check (bucket_id = 'published-cvs' and ops.is_staff())$p$;
  execute $p$create policy published_cvs_update on storage.objects
    for update to authenticated using (bucket_id = 'published-cvs' and ops.is_staff())
    with check (bucket_id = 'published-cvs' and ops.is_staff())$p$;
  execute $p$create policy published_cvs_delete on storage.objects
    for delete to authenticated using (bucket_id = 'published-cvs' and ops.is_staff())$p$;
end
$$;

-- The view gains cv_path. A column cannot be added to the middle of a view in
-- place, and the order matters less than keeping this definition identical to
-- the one in 0002_security.sql, so that either file can be run again in any
-- order and leave the same view behind.
drop view if exists public.published_workers;

create view public.published_workers as
  select
    a.id,
    a.english_name,
    a.arabic_name,
    a.gender,
    extract(year from age(a.dob))::int as age,
    a.country,
    a.profession,
    a.type,
    a.experience_years,
    a.photo_path,
    a.cv_path,
    a.updated_at
  from ops.applicants a
  where a.published_to_website
    and a.status = 'Available';

comment on view public.published_workers is
  'Public projection for eleutheria.agency. Add columns here deliberately: anything listed becomes world readable.';

grant select on public.published_workers to anon, authenticated;


-- ======================================================== 0007_public_projection.sql --

-- What the website is allowed to see, and how it is allowed to see it.
--
-- The rule has not changed: enough to present a worker and nothing that
-- identifies her beyond it. Date of birth is reduced to an age; passport,
-- identity, phone and every financial column are simply absent.
--
-- How it is served has changed, because the first arrangement invited its own
-- undoing. A plain view in `public` reading a locked table runs with its
-- owner's rights, and Supabase's database linter reports that as a security
-- definer view -- correctly, as a description, and misleadingly as a warning,
-- since running with the owner's rights is the entire point. Accepting the
-- linter's offered fix sets security_invoker on, the anonymous caller loses
-- the owner's rights along with it, and the website goes dark.
--
-- So the pieces are arranged to leave nothing for anyone to fix:
--
--   * a function does the reading. It is security definer, which is where the
--     borrowed rights now live, and its search_path is pinned so the name
--     ops.applicants cannot be made to mean anything else.
--   * the function belongs to a role of its own, ops_website_reader, which
--     cannot log in and exists for this one job. A single policy on
--     ops.applicants lets that role read a published, available row and
--     nothing else. Row level security is forced on that table, and forced
--     means forced, so without the policy even the owner's rights read
--     nothing -- and because the policy names this role alone, a signed-in
--     stranger gains nothing from it.
--   * the view is security_invoker, so the linter has nothing to say. The
--     anonymous caller needs no rights on any table -- only permission to run
--     the function, which decides for itself what comes back.
--
-- The upshot is that `anon` is granted nothing on ops.applicants, here or
-- anywhere, and the twelve columns below are the whole of what the internet
-- can reach.

do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'published_workers' and table_type = 'BASE TABLE'
  ) then
    raise exception 'public.published_workers already exists as a table. Rename it or change this view''s name before running this migration.';
  end if;
end
$$;

-- The role the reading is done as. It cannot log in, holds nothing but the one
-- grant below, and exists so that the permission to read published rows can be
-- given to a job rather than to a person or to everybody.
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'ops_website_reader') then
    create role ops_website_reader nologin noinherit;
  end if;
end
$$;

-- Owning a function means being able to hand it over: on some versions the
-- creator is an administrator of the role it just made, on others the
-- membership has to be asked for. Either way this is a no-op the second time.
do $$
begin
  execute format('grant ops_website_reader to %I', current_user);
exception when others then
  null;
end
$$;

grant usage on schema ops to ops_website_reader;
grant select on ops.applicants to ops_website_reader;

-- A published, available worker may be read -- by this role, and by no other.
-- Every other policy on this table is `to authenticated`, and this one stays
-- out of their way: a signed-in stranger with no staff row still reads nothing.
drop policy if exists website_published_read on ops.applicants;
create policy website_published_read on ops.applicants
  for select to ops_website_reader
  using (published_to_website and status = 'Available');

create or replace function ops.published_workers_rows()
returns table (
  id               uuid,
  english_name     text,
  arabic_name      text,
  gender           text,
  age              int,
  country          text,
  profession       text,
  type             text,
  experience_years smallint,
  photo_path       text,
  cv_path          text,
  updated_at       timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    a.id,
    a.english_name,
    a.arabic_name,
    a.gender,
    extract(year from age(a.dob))::int,
    a.country,
    a.profession,
    a.type,
    a.experience_years,
    a.photo_path,
    a.cv_path,
    a.updated_at
  from ops.applicants a
  where a.published_to_website
    and a.status = 'Available';
$$;

comment on function ops.published_workers_rows() is
  'The public projection for eleutheria.agency. Add columns here deliberately: anything returned becomes world readable.';

-- Nobody runs this by accident: the grant is named, not inherited from public.
revoke all on function ops.published_workers_rows() from public;
grant usage on schema ops to anon;
grant execute on function ops.published_workers_rows() to anon, authenticated;

-- Handed over last, so that the revoke and the grants above are made by the
-- role that still owns it at the time.
alter function ops.published_workers_rows() owner to ops_website_reader;

-- A view rather than an rpc endpoint, so the website keeps reading a table-
-- shaped thing it can filter and order in the ordinary way.
drop view if exists public.published_workers;

create view public.published_workers
  with (security_invoker = true)
  as select * from ops.published_workers_rows();

comment on view public.published_workers is
  'Public projection for eleutheria.agency. The columns come from ops.published_workers_rows(); change them there.';

grant select on public.published_workers to anon, authenticated;
